async-openai/Cargo.toml
async-openai/README.md
async-openai/src/client.rs
async-openai/src/download.rs
async-openai/src/error.rs
async-openai/src/file.rs
async-openai/src/image.rs
async-openai/src/lib.rs
async-openai/src/types.rs
async-openai/src/util.rs

- types supporting list, delete, retrieve, retrieve contents for an OpenAIFile
- unit test to test all the functions (except retrieve contents as it is not allowed for free accounts)
- use generic error names `FileSaveError`, `FileReadError` for file related errors in `file.rs` module or `image.rs` module

Support for File (OpenAIFile)

---

async-openai/Cargo.toml
async-openai/README.md
async-openai/src/client.rs
examples/Cargo.toml
examples/rate-limit-completions/Cargo.toml
examples/rate-limit-completions/src/main.rs

- Retry with exponential backoff on rate limits
- Only non stream requests are retried. Form submissions are not retried. 
- Add example to send back to back requests to trigger rate limit and retries.

Handle rate limiting

---

async-openai/Cargo.toml
async-openai/src/client.rs
async-openai/src/error.rs
async-openai/src/lib.rs
examples/rate-limit-completions/Cargo.toml
examples/rate-limit-completions/src/main.rs

- Support `OpenAI-Organization: my-org` header 
- Add tracing to log warning when a request is rate limited
- Update `rate-limit-completions` example to actually log the rate limit warning (previous this would be siliently retried without any feedback to library user - logging makes it visibile to the library user)

Support for Organization id header; Support to log rate limit warning

---

async-openai/README.md
async-openai/src/client.rs
async-openai/src/completion.rs
async-openai/src/embedding.rs
async-openai/src/fine_tune.rs
async-openai/src/lib.rs
async-openai/src/types.rs
examples/codex/src/main.rs
examples/completions-stream/src/main.rs
examples/completions/src/main.rs
examples/create-edit/src/main.rs
examples/create-image-b64-json/src/main.rs
examples/create-image-edit/src/main.rs
examples/create-image-variation/src/main.rs
examples/create-image/src/main.rs
examples/models/src/main.rs
examples/moderations/src/main.rs
examples/rate-limit-completions/src/main.rs

- Fine-tunes: list events using SSE streaming `FineTunes::list_events_stream`
- Update request types: mostly to accommodate `string or array` variants
- Updated examples to use updated types
- Remove `use async_openai as openai`  from everywhere; instead just use the regular `use async_openai` as it is.

feat: Fine tune events stream; Most complete request-response Rust types

---

async-openai/src/client.rs

Using `Client::default()` to create a Client does not set the default api_base, it will crash when sending request;
The purpose of this pr is to use `Client::default()` to create a Client and set the correct default parameters

feat: Create Client with Client::default(); use default parameters

---

async-openai/src/client.rs
async-openai/src/types/types.rs
async-openai/tests/boxed_future.rs

This is needed so the types can be sent between threads in a multithreaded runtime.
https://github.com/64bit/async-openai/issues/36
Thank you.

Adding Send bound to boxed future types

---

async-openai/Cargo.toml
async-openai/README.md
async-openai/src/download.rs
async-openai/src/embedding.rs
async-openai/src/file.rs
async-openai/src/fine_tune.rs
async-openai/src/image.rs
async-openai/src/model.rs
async-openai/src/moderation.rs
async-openai/src/types/types.rs

- upgrade crate dependencies to latest ( only base64 has breaking change)
- update links from `beta.openai.com` to `platform.openai.com`

Upgrade dependencies and update doc links

---

async-openai/README.md
async-openai/src/chat.rs
async-openai/src/client.rs
async-openai/src/file.rs
async-openai/src/lib.rs
async-openai/src/types/types.rs
async-openai/tests/boxed_future.rs

Closes #42 
I moved the chat functions to a new file because `chat().create()` seemed cleaner than `completions().create_chat()`, but let me know if that's preferred.

Support for ChatGPT API

---

async-openai/src/types/types.rs

finish_reason can sometimes be null in CreateChatCompletionResponse.

ChatChoice finish_reason can be null

---

async-openai/src/types/types.rs
examples/chat-stream/src/main.rs
examples/chat/src/main.rs

- Add the `max_tokens` field to the `CreateChatCompletionRequest` struct.
- Updated example to verify behavior
Test plan:
Run chat and chat-stream examples locally
Closes #49

feat: Add max_tokens for chat completion requests

---

async-openai/src/types/types.rs

This Pr should fix `Error: invalid_request_error: None is not of type 'string' - 'user'` error from the API.
On latest version of the library my requests are failing with the mentioned error. I assume this is because serde json will be default populate the field with `"null"` and the API expects it to be missing if it's not set?
`skip_serializing_if ` is already implemented on a lot of other fields and I suspect that it might also need to be added to others

Fix: invalid_request_error: None is not of type 'string' - 'user'

---

async-openai/src/types/types.rs

CreateChatCompletionRequests can be serialized and written to output.  By deriving Deserialize on the following enums/structs, output can be serialized to a file then read and deserialized to allow continuing of conversations. 
PS: This is my first attempt at contributing to an open source project.  Please let me know if I went about anything wrong and I apologize if if this was not the proper way to go about this. Thank you for the library!

Allow CreateChatCompletionRequests to be deserialized

---

async-openai/src/types/types.rs

Hey!
I originally only wanted to make `Usage` clonable because I was trying to pass it around and realise you can't clone it.
But looking at it I noticed that a lot of the API types don't have clone so I added it because it makes working with them easier.
I think some of them could even do with copy since they can be bitwise copied but didn't want to go around randomly adding things that I didn't need yet.
Let me know what you think! Happy to remove a lot of these clones if if you think I put them on types that shouldn't have them!

Make API types clonable

---

async-openai/src/client.rs

Creating new `reqwest::Client` on each request prevents `reqwest` from leveraging its connection pool, leading to unnecessary TCP handshakes.

Re-use `reqwest::Client` and allow users to customize it

---

async-openai/Cargo.toml

This pull request adds support for rustls, allowing users to switch between options.

feat: Add rustls support

---

async-openai/src/client.rs
async-openai/src/download.rs
async-openai/src/error.rs

Retain more information for better visibility to library user. 
1. When de-serialization fails, we log the payload responsible though `tracing::error!(...)`
2. When file download or save fails we retain the directory / file path / url in the error String.

retain useful information when error occurs

---

async-openai/src/types/types.rs

This allows response types to be easily cached or stored for test examples.
The main downside is additional generated code.
https://github.com/64bit/async-openai/issues/65

Implement Serialize for all response types

---

async-openai/Cargo.toml

Hey, first of all thanks for the awesome crate.
I run my rust services on ARM-based AWS graviton instances which have a different version of OpenSSL that doesn't play nicely with reqwest. This diff adds a new feature to async-openai that allows removing the dependency on OpenSSL by opting in for the native-tls-vendored feature in the reqwest library. 
I've tested this on graviton with an incompatible version of OpenSSL and things work nicely :)
Thanks

Add reqwest/native-tls-vendored feature

---

async-openai/src/config.rs

Hello! Thanks for this crate, which I'm using in my projects.
I found the bug: even if you specify api base in the config, the client will replace it when making a request (for openai config). So, this is the fix :)

Fix api base in url

---

async-openai/README.md

This pull request is in response to issue #87.  Also, since I opened this, @WestXu asked about integration with [clap](https://github.com/clap-rs/clap), which I've done now and it's pretty fun. You can see an example of integrating async-openai with clap [here](https://github.com/frankfralick/openai-func-enums#integration-with-clap). Thanks again.

Link to openai-func-enums

---

async-openai/src/client.rs
async-openai/src/error.rs

Made `ApiError::r#type` an optional string to support the mismatch between Azure and OpenAI's specification. This will at least let Azure users view the actual error instead of receiving JSON Deserialization errors.
Discussed in #94

Made ApiError `r#type` optional to support Azure Error responses

---

async-openai/src/config.rs

This should close #107. Arguably, the deserialization uses `Default` when a field is not given during deserialization and thus is too permissive. As far as I know,  Azure APIs needs all fields in `AzureConfig` to be valid ones, but the defaults are not.

add  deserialization for OpenAIConfig and AzureConfig

---

async-openai/src/types/types.rs

Enums that do not store additional data can be copied around.

Derive Copy for enums

---

async-openai/src/client.rs

A good practice in production environments is to have multiple clients from multiple endpoints and api keys to increase reliability and throughput. But, managing these different clients can be hectic as some fail. Providing a way to debug more easily by exposing the config would be great. A workaround would be to wrap every client in a container with the config info, but it's not ideal.
This simply exposes `Config` parameter so we can do something like `client.config().api_base()`

Expose `Config`

---

async-openai/src/types/impls.rs
async-openai/src/types/types.rs

According to [OpenAI's docs](https://platform.openai.com/docs/api-reference/chat/create), the `function_call` parameter can only be either `none`, `auto`, or `{ "name": function_name }`.
The current interface in this library feels counter-intuitive, and I've often tried to call a custom function using `ChatCompletionFunctionCall::String(function_name)` instead of `ChatCompletionFunctionCall::Object(json!({ "name": custom_function }))`.
This change proposes a more intuitive interface for this (as a breaking change unfortunately).

Better ChatCompletionFunctionCall interface

---

async-openai/README.md
async-openai/src/chat.rs
async-openai/src/client.rs
async-openai/src/completion.rs
async-openai/src/file.rs
async-openai/src/fine_tuning.rs
async-openai/src/image.rs
async-openai/src/lib.rs
async-openai/src/moderation.rs
async-openai/src/types/impls.rs
async-openai/src/types/types.rs
examples/function-call-stream/src/main.rs
openapi.yaml

Sync changes from upstream spec:
- use enums `FinishReason` & `CompletionFinishReason` for `finish_reason` instead of `String`
- Rename struct `Usage` to `CompletionUsage`
- Add field `encoding_format` in `CreateEmbeddingRequest`
- Update `status_detail` field type in `OpenAIFile` from object to `String`
- Rename `ImageData` to `Image` to match spec
- Rename `ImageResponse` to `ImagesResponse` to match spec
- Add new fields in moderation request and response types.
- Update doc comments to match latest spec 
- Add new Fine Tuning APIs
- Mark `Edit` and `FineTunes` to be deprecated
- Update `ChatCompletionFunctionCall` for better DX

Updates from latest upstream spec

---

async-openai/Cargo.toml
async-openai/README.md
async-openai/src/audio.rs
async-openai/src/client.rs
async-openai/src/types/types.rs
examples/audio-speech/.gitignore
examples/audio-speech/Cargo.toml
examples/audio-speech/README.md
examples/audio-speech/src/main.rs

- Added a `post_raw` and `execute_raw` internal functions, since we don't want to JSON-decode the response body for the speech endpoints (which return raw audio). Modified the `execute` function to wrap around `execute_raw`.
- Added basic support for the TTS api
Note that the struct corresponding to the `response_format` parameter was named `SpeechResponseFormat` instead of `AudioResponseFormat`, since the later already existed for defining whisper response formats.
I'd love to add an enum for voices as well (with an Other wildcard and marked as non-exhaustive), but refrained since the library's pattern seems to be deferring to strings (same case as model IDs all across).

Add speech endpoint

---

async-openai/src/types/assistants/run.rs

Sometimes Run retreivals fail with message that it couldn't convert null to i32. Looks like expires_at is actually optional, see example in https://platform.openai.com/docs/api-reference/runs
Change its type from i32 to Optional<i32>. The problem was resolved after this change.

Make Run.expires_at optional

---

async-openai/src/types/assistants/run.rs

Field SubmitToolOutputsRunRequest.tools_outputs has a typo. It should be be called tool_outputs instead.
This PR renames it to tool_outputs and fixes deserialization.

Rename tools_outputs to tool_outputs

---

examples/tool-call-stream/Cargo.toml
examples/tool-call-stream/src/main.rs
examples/tool-call/Cargo.toml
examples/tool-call/src/main.rs

This PR adds non-streaming and streaming examples of chat completions with tool calls. These two examples are fairly close to the function-call and function-call-stream examples that use the deprecated parts of api. These examples keep the "get_current_weather" function but change the prompt to ask for the weather in two locations. This is to induce multiple tool calls in order to demonstrate dealing with the possibility of parallel tool calls.
This should address issue #143 (provide tool call examples) and issue #151 (provide example handling parallel/multiple tool calls).

Add examples tool-call and tool-call-stream

---

async-openai/src/types/types.rs

Setting this to `auto` was causing my requests to fail because of malformed values in the `tool_choice` filed.
I think the OpenAI API is expecting these values to be lowercase but "Auto" will be capitalised.
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice
I only tested this with the "Auto" value. But I assume this should also work for the other variants

Fix: Make ChatCompletionToolChoiceOption enum variants lowercase

---

async-openai/src/client.rs
async-openai/tests/whisper.rs

this pr may resolve #140.
Before the fix, call audio transcription resulted in the following error:
```rust
#[tokio::test]
async fn multipart_form_test() {
let client = Client::new();
// https://github.com/64bit/async-openai/issues/140
let transcribe_task = tokio::spawn(async move { 
transcribe(client).await 
});
let result = tokio::join!(transcribe_task);
println!("transcribe: {:?}", result.0);
}
async fn transcribe(client: Client<OpenAIConfig>) -> Result<String, OpenAIError> {
// Credits and Source for audio: https://www.youtube.com/watch?v=oQnDVqGIv4s
let request = CreateTranscriptionRequestArgs::default()
.file(
"../examples/audio-transcribe/audio/A Message From Sir David Attenborough A Perfect Planet BBC Earth_320kbps.mp3"
)
.model("whisper-1") …
```

Fix: post_form to be Sendable

---

async-openai/src/types/assistant.rs

@64bit 
All fields (including model) are optional in OpenAI API.

Optional model in ModifyAssistantRequest

---

examples/cloudflare-wasm-worker/.gitignore
examples/cloudflare-wasm-worker/Cargo.toml
examples/cloudflare-wasm-worker/README.md
examples/cloudflare-wasm-worker/package-lock.json
examples/cloudflare-wasm-worker/package.json
examples/cloudflare-wasm-worker/src/lib.rs
examples/cloudflare-wasm-worker/wrangler.toml

This adds a working cloudflare wasm worker example. 
A remaining issue is that this example must be moved out of the parent `async-openai` directory to get compiled, because `cargo` resolves dependencies of examples altogether, but `wasm-bindgen` causes conflicts between this example and openai-web-app example. This one uses older `wasm-bindgen` while the other requires newer one.
If the example is enough, you can also consider merging the code in experiments branch into main.

Add cloudflare wasm worker example

---

async-openai/src/embedding.rs
async-openai/src/types/embedding.rs

Added the dimensions param to the embedding request so that shortened embeddings can optionally be requested.

Added dimensions param to embedding request

---

async-openai/Cargo.toml
async-openai/README.md
async-openai/src/embedding.rs
async-openai/src/file.rs
async-openai/src/types/chat.rs
async-openai/src/types/completion.rs
async-openai/src/types/embedding.rs
async-openai/src/types/fine_tune.rs

This syncs the changes from main to experiments branch. The code compiles fine on all targets.

Sync experiments branch with main 0.18.2

---

async-openai/src/types/impls.rs

When I was using the api `/v1/audio/transcriptions` , I found that the language conversion function was not working properly, and I fixed it! 😊 
issue is there: #187

fix: CreateTranscriptionRequest language field not convert

---

async-openai/src/types/run.rs

OpenAI provide usage information on the run object, this PR adds that information to the RunObject in async_openai.
OpenAI documentation:
https://platform.openai.com/docs/api-reference/runs/object#runs/object-usage

Add usage information to the run object

---

examples/assistants/src/main.rs

Resolves #194 .
Using `std::thread::sleep` in async code is not advisable. `tokio::time::sleep` is preferred instead. This PR contains this small change. 
Tested the code change by running locally - works as expected!

Making the sleep asynchronous compatible in an example

---

examples/vision-chat/Cargo.toml
examples/vision-chat/README.md
examples/vision-chat/src/main.rs

The example directory currently lacks an example that matches the quickstart from https://platform.openai.com/docs/guides/vision 
This PR adds the quickstart example. Notably it shows how to use `ChatCompletionRequestMessageContentPartTextArgs`, `ChatCompletionRequestMessageContentPartImageArgs`, `ImageUrlArgs` and `ImageUrlDetail`. 
I followed the logic from the standard chat example.
Please let me know if I can improve the PR and thank you very much for creating this crate.

Add vision-chat example

---

async-openai/src/audio.rs
async-openai/src/client.rs
async-openai/src/types/audio.rs
async-openai/src/types/impls.rs
examples/audio-transcribe/src/main.rs

This PR adds support for `AudioResponseFormat::VerboseJson` and `TimestampGranularity`, including updated example code. These were defined as types before, but not fully implemented.
Implements 64bit/async-openai#201.
Please let me know if I can improve this PR! And thank you for a very helpful crate.

Update Audio APIs from updated spec

---

async-openai/Cargo.toml
examples/vision-chat/src/main.rs

Waiting https://github.com/jpopesculian/reqwest-eventsource/pull/20

Upgrade dependencies: Rust crates in Cargo.toml

---

async-openai/src/lib.rs
async-openai/src/types/impls.rs
async-openai/tests/boxed_future.rs

- updated models in test that no longer exists
- Prevent doctest for doc string not a valid code in the crate

test: cargo test working

---

async-openai/src/types/message.rs

Made `pub quote: Option<String>`, optional as suggested, seems to work fine now, cheers

fix FileCitation deserialization

---

async-openai/src/types/assistant.rs

Otherwise the server fails with 500.

assistant: don't send null values for tool resources

---

async-openai/src/types/vector_store.rs
async-openai/src/vector_store_files.rs

This targets the changes mentioned in #229, because OpenAI requires a non-null name when creating a vector store. This also fixes attaching a file to a vector store, where it would fail to deserialize. Also adds a test for both errors to catch them during development in the future!
Fixes #229

fix: Update vector store file chunking strategy to use StaticChunkingStrategy

---

async-openai/src/audio.rs
async-openai/src/types/chat.rs
async-openai/src/types/message.rs
async-openai/src/types/run.rs
async-openai/src/types/thread.rs
async-openai/src/types/vector_store.rs
async-openai/src/vector_store_files.rs
examples/assistants-file-search/src/main.rs
examples/audio-translate/src/main.rs
openapi.yaml

- updates from spec: parallel_tool_calls
- Add `Audio::translate_raw` for SRT format support

spec updates; audio translate SRT support

---

async-openai/src/lib.rs
async-openai/src/types/chat.rs
async-openai/src/types/completion.rs
async-openai/tests/boxed_future.rs
examples/azure-openai-service/src/main.rs
examples/chat-stream/src/main.rs
examples/chat/src/main.rs
examples/completions-stream/src/main.rs
examples/completions/src/main.rs
examples/function-call-stream/src/main.rs
examples/function-call/src/main.rs
examples/tool-call-stream/src/main.rs
examples/tool-call/src/main.rs
examples/vision-chat/src/main.rs

Closes https://github.com/64bit/async-openai/issues/232

Change max_tokens type to Option<u32>

---

async-openai/src/types/run.rs

fix: skip serialization to null if field is none in `CreateRunRequest`

---

async-openai/src/error.rs

Fixes #238 
I tested with one variation ("too many tokens") and it works fine. Tough to test exhaustively of course.

Make error message for `ApiError` more user-friendly

---

async-openai/src/types/vector_store.rs

I tried listing my vector store file and received the following error.
```
value: JSONDeserialize(Error("unknown variant `unsupported_file`, expected one of `internal_error`,
`file_not_found`, `parsing_error`, `unhandled_mime_type`", line: 204, column: 34))
```
Doing the API call manually I saw that the status code returned is not yet supported in `async-aponai`.
```bash
curl https://api.openai.com/v1/vector_stores/vs_Y.../files -H 'OpenAI-Beta: assistants=v2'
```
the response.
```json
{
"id": "file-hAV...",
"object": "vector_store.file",
"usage_bytes": 0,
"created_at": 1722070582,
"vector_store_id": "vs_....",
"status": "failed",
"last_error": {
"code": "unsupported_file",
"message": "The file type is not supported."
},
"chunking_strategy": {
"type": "static",
"static": { …
```

add unsupported_file error type for vector_store.file

---

async-openai/src/types/assistant.rs

For `CreateAssistantToolFileSearchResources` struct the API expects only one of the two fields to be used. Even an empty array is not accepted if the other field contains a value. Thus making both `vector_store_ids` and `vector_stores` optional is the way to go.
Fixes 64bit/async-openai#251

Fix incompatibility with API requirements

---

async-openai/src/types/chat.rs

As per the API reference page on OpenAI's website, the parameter can be excluded from the request.
https://platform.openai.com/docs/api-reference/chat

Fix service_tier serialization for CreateChatCompletionRequest

---

async-openai/src/types/chat.rs

They are optional per the openai docs.

Fix content, refusal serialization for CreateChatCompletionRequest

---

async-openai/src/types/assistant.rs
async-openai/src/types/vector_store.rs

This PR fixes three issues with chunking strategies in the vector stores API:
1. Incorrect serialization format for static chunking strategy
2. Incorrect casing in enum variant serialization ("Static" vs "static")
3. Private fields preventing users from setting chunking parameters
The OpenAI API expects the static chunking configuration to be nested under a "static" field, but the current implementation serializes it directly. This causes the error:
```
"Missing required parameter: 'chunking_strategy.static'."
```
Additionally, the enum variants were serializing with incorrect casing, causing:
```
"Invalid value: 'Static'. Supported values are: 'auto' and 'static'."
```
Changed from:
```rust
#[derive(Clone, Serialize, Debug, Deserialize, PartialEq, Default)]
#[serde(tag = "type")]
pub …
```

Fix chunking strategy serialization and field visibility

---

async-openai/src/types/realtime/session_resource.rs

As per the docs at https://platform.openai.com/docs/api-reference/realtime-client-events/session/update
The name for MaxOutputTokens is `max_response_output_tokens`. I've renamed the enum and attribute accordingly.

Rename max output tokens as per api docs

---

async-openai/src/types/chat.rs
examples/chat-store/Cargo.toml
examples/chat-store/README.md
examples/chat-store/src/main.rs

Solves #298 by adding support for store flag and metadata JSON for tags in chat
- CreateChatCompletionRequest updated
- Add example: /example/chat-store 
- Match examples in https://platform.openai.com/docs/guides/distillation and https://platform.openai.com/docs/guides/evals

Add store and metadata parameters

---

async-openai/Cargo.toml
async-openai/src/config.rs

Updates Secrecy to the latest version. Because the api changed, this is unfortunately a breaking change (swiftide included 🤷).
However, probably best to keep secret managing libraries up to date.
Thanks for the great library, we use it *a lot*.

chore(deps)!: Update Secrecy

---

examples/structured-outputs-schemars/Cargo.toml
examples/structured-outputs-schemars/README.md
examples/structured-outputs-schemars/src/main.rs

Use `serde` and `schemars` to write structure output example.

[Example]: Use serde, schemars to make structure output code easy

---

async-openai/Cargo.toml
async-openai/src/client.rs
async-openai/src/types/impls.rs
async-openai/src/util.rs

This fixes #316 
As per https://github.com/rust-lang/api-guidelines/discussions/231, the increase of MSRV is not a breaking change, so there's no need for a major release.

remove async-convert and bump rust-version

---

async-openai/src/types/impls.rs

In trying to use the new `ChatCompletionRequestDeveloperMessage` added in #312, I found I couldn't use `.into()` to add it to `messages` because a `From<ChatCompletionRequestDeveloperMessage>` implementation for `ChatCompletionRequestMessage` wasn't available.

Add `From<ChatCompletionRequestDeveloperMessage>` implementation for `ChatCompletionRequestMessage`

---

examples/ollama-chat/.gitignore
examples/ollama-chat/Cargo.toml
examples/ollama-chat/README.md
examples/ollama-chat/docker-compose.yml
examples/ollama-chat/ollama_entrypoint.sh
examples/ollama-chat/src/main.rs

Fixes #191. 
I used the code examples from https://github.com/64bit/async-openai/issues/173 as a starting point and tried to simplify them to match the existing chat example.

Add simple ollama chat example

---

async-openai/src/client.rs

Hi! Thanks for creating and maintaining async-openai. I noticed during the outtages last weekend that the client is not dealing with server errors as is instructed by OpenAI.
I'm fairly certain these are new instructions, on this page you can see:
https://platform.openai.com/docs/guides/error-codes
That they are now advising to retry (after a delay) on any server error.
It is slightly more involved than that, because I also noticed that it is sometimes (always?) the case that they do not return JSON on server errors, so instead of parsing JSON, we need to create the `ApiError` ourselves by simply inserting the whole response body into the message.

Backoff when OpenAI returns 5xx

---

async-openai/src/types/audio.rs
openapi.yaml

- support the new `instructions` parameter for text-to-speech
- document this field in the OpenAPI spec
Note, I updated the OpenAPI spec manually - let me know if I should regenerate it instead.

Add instructions option to speech request

---

async-openai/src/types/responses.rs

In the current Responses API implementation for the Vector Store, not all states are implemented. This PR is adding the missing state, so vector store lookups no longer fail with 
```
thread 'tokio-runtime-worker' panicked at src/main.rs:140:71:
called `Result::unwrap()` on an `Err` value: JSONDeserialize(Error("unknown variant `completed`, expected one of `in_progress`, `searching`, `incomplete`, `failed`", line: 28, column: 4))
```

Responses API - add missing completed state

---

async-openai/src/types/audio.rs
openapi.yaml

Hey folks. I was parsing a config file based on the voice options here: https://platform.openai.com/docs/guides/text-to-speech#voice-options
and I got an error that "ballad" is not an expected option. I added it to the enum. 
I didn't see any test to update. Let me know if there's anything missing.

Add missing voice Ballad to enum

---

async-openai/src/types/realtime/response_resource.rs
async-openai/src/types/realtime/server_event.rs
async-openai/src/types/realtime/session_resource.rs

- Added `Cancelled` variant to `ResponseStatusDetail` enum for better handling of cancelled responses.
- Introduced `LogProb` struct to capture log probability information for transcribed tokens.
- Updated `ConversationItemInputAudioTranscriptionCompletedEvent` and `ConversationItemInputAudioTranscriptionDeltaEvent` to include optional `logprobs` for per-token log probability data.
- Enhanced `AudioTranscription` struct with optional fields for `language`, `model`, and `prompt` to improve transcription accuracy and customization.
- Added new `SemanticVAD` option in the `TurnDetection` enum to control model response eagerness.
- Expanded `RealtimeVoice` enum with additional voice options for more variety in audio responses.

feat: enhance realtime response types and audio transcription options

---

async-openai/src/types/chat.rs
async-openai/src/types/impls.rs

Updates the `Prompt` enum to use `u32` instead of `u16` for integer-based prompt representations. The change affects both `Prompt::IntegerArray` and `Prompt::ArrayOfIntegerArray` variants, as well as associated `impl_from_for_*` macro implementations.
The original use of `u16` may have been based on the assumption that token ID values would not exceed the vocabulary size of models like GPT-2 or GPT-3 (i.e. 50256 tokens). 
While that assumption held previously, newer models frequently exceed this range. Allowing `u32` values would enable inference libraries to use `u32` token IDs and larger vocabulary sizes without needing to truncate while batching.
I fully recognize this is a breaking change to the public API:
- Users of `Prompt::IntegerArray` or `Prompt::ArrayOfIntegerArray` with `u16` …

feat: change Prompt integer variants from u16 to u32 for future compatability

---

async-openai/Cargo.toml
async-openai/src/error.rs
async-openai/src/lib.rs

Hi! thanks for the great ilbrary! I would love to see if you'd be open to adding a `Serialize` impl to the `ApiError` type so it can round trip. 
I also bumped the Cargo.toml version so a new crate version could be published, if you are able to do that after merging that would be awesome. 
The diff in `async-openai/src/lib.rs` was from running `cargo fmt`

task: Add serialize impl for ApiError

---

async-openai/src/util.rs

OpenAI API seems to be accepting files without specifying mime to be "application/octet-stream"

fix: remove hardcoded mime_str

---

async-openai/src/types/chat.rs

Fix typo in `ChatCompletionToolChoiceOption` docs

---

async-openai/src/types/chat.rs

Adds the new `minimal` reasoning effort for gpt 5. There's so much room for puns here, but I'll leave it open to interpretation.
https://platform.openai.com/docs/guides/latest-model#minimal-reasoning-effort

feat: Add `minimal` reasoning effort for gpt-5

---

async-openai/src/types/chat.rs

The new [3.1.0 spec](https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml) added variants to the ServiceTier
```yaml
ServiceTier:
type: string
description: |
Specifies the processing type used for serving the request.
- If set to 'auto', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use 'default'.
- If set to 'default', then the request will be processed with the standard pricing and performance for the selected model.
- If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)' or '[priority](https://openai.com/api-priority-processing/)', then the request will be processed with the corresponding service tier.
- When not set, the default behavior is 'auto'. …
```

add Scale and Priority to ServiceTier

---

async-openai/src/types/responses.rs

The response filters had a typo/mistake where the wrong comparison type is used in a compound filter.
We want options like AND or OR not Equals, NEquals etc.
https://platform.openai.com/docs/api-reference/responses/create

fix: CompoundFilter should use CompoundType instead

---

async-openai/src/types/responses.rs

- According to OpenAI's [specification](https://platform.openai.com/docs/api-reference/responses/object#responses/object-output), `OutputItem` should be a tagged union. This PR updates that struct to align with OpenAI's specification
- A nice benefit of this is that streaming with tool calls is now supported

fix: Update `OutputItem` to align with OpenAI's Specification
